/*
 * generated by Xtext 2.10.0
 */
package pucrs.lp.turtle.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import pucrs.lp.turtle.turtle.Model

@RunWith(XtextRunner)
@InjectWith(TurtleInjectorProvider)
class TurtleParsingTest{

	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void testFoward(){
		val result = parseHelper.parse('''
			fd 30
		''')
		Assert.assertNotNull(result)
	}

}
