/*
 * generated by Xtext 2.10.0
 */
package pucrs.lp.turtle.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTurtleScopeProvider extends DelegatingScopeProvider {
}
