/**
 * generated by Xtext 2.10.0
 */
package pucrs.lp.turtle.turtle;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Foward</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see pucrs.lp.turtle.turtle.TurtlePackage#getFoward()
 * @model
 * @generated
 */
public interface Foward extends Command
{
} // Foward
