/**
 * generated by Xtext 2.10.0
 */
package pucrs.lp.turtle.turtle;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rotate</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see pucrs.lp.turtle.turtle.TurtlePackage#getRotate()
 * @model
 * @generated
 */
public interface Rotate extends Command
{
} // Rotate
