/**
 * generated by Xtext 2.10.0
 */
package pucrs.lp.turtle.turtle.impl;

import org.eclipse.emf.ecore.EClass;

import pucrs.lp.turtle.turtle.Foward;
import pucrs.lp.turtle.turtle.TurtlePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Foward</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FowardImpl extends CommandImpl implements Foward
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FowardImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TurtlePackage.Literals.FOWARD;
  }

} //FowardImpl
