/**
 * generated by Xtext 2.10.0
 */
package pucrs.lp.turtle.turtle.impl;

import org.eclipse.emf.ecore.EClass;

import pucrs.lp.turtle.turtle.Rotate;
import pucrs.lp.turtle.turtle.TurtlePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rotate</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RotateImpl extends CommandImpl implements Rotate
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RotateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TurtlePackage.Literals.ROTATE;
  }

} //RotateImpl
